Y_PIXEL = "Y_PIXEL"
TIME_SLEEP = "TIME_SLEEP"
SLEEP_TIME = 0.07  # 射速
y_1=40
scar_data1 = [
    {Y_PIXEL: y_1, TIME_SLEEP: SLEEP_TIME},
    {Y_PIXEL: y_1, TIME_SLEEP: SLEEP_TIME},
    {Y_PIXEL: y_1, TIME_SLEEP: SLEEP_TIME},
    {Y_PIXEL: y_1, TIME_SLEEP: SLEEP_TIME},
    {Y_PIXEL: y_1, TIME_SLEEP: SLEEP_TIME},

]
y_2=77
scar_data2 = [
    {Y_PIXEL: y_2, TIME_SLEEP: SLEEP_TIME},
    {Y_PIXEL: y_2, TIME_SLEEP: SLEEP_TIME},
    {Y_PIXEL: y_2, TIME_SLEEP: SLEEP_TIME},
    {Y_PIXEL: y_2, TIME_SLEEP: SLEEP_TIME},
    {Y_PIXEL: y_2, TIME_SLEEP: SLEEP_TIME},
]
y_3=75
scar_data3 = [
    {Y_PIXEL: y_3, TIME_SLEEP: SLEEP_TIME},
    {Y_PIXEL: y_3, TIME_SLEEP: SLEEP_TIME},
    {Y_PIXEL: y_3, TIME_SLEEP: SLEEP_TIME},
    {Y_PIXEL: y_3, TIME_SLEEP: SLEEP_TIME},
    {Y_PIXEL: y_3, TIME_SLEEP: SLEEP_TIME},
]
y_4=55+32
scar_data4 = [
    {Y_PIXEL: y_4, TIME_SLEEP: SLEEP_TIME},
    {Y_PIXEL: y_4, TIME_SLEEP: SLEEP_TIME},
    {Y_PIXEL: y_4, TIME_SLEEP: SLEEP_TIME},
    {Y_PIXEL: y_4, TIME_SLEEP: SLEEP_TIME},
    {Y_PIXEL: y_4, TIME_SLEEP: SLEEP_TIME},
]
y_5=80
scar_data5 = [
    {Y_PIXEL: y_5, TIME_SLEEP: SLEEP_TIME},
    {Y_PIXEL: y_5, TIME_SLEEP: SLEEP_TIME},
    {Y_PIXEL: y_5, TIME_SLEEP: SLEEP_TIME},
    {Y_PIXEL: y_5, TIME_SLEEP: SLEEP_TIME},
    {Y_PIXEL: y_5, TIME_SLEEP: SLEEP_TIME},
]
y_6=90
scar_data6 = [
    {Y_PIXEL: y_6, TIME_SLEEP: SLEEP_TIME},
    {Y_PIXEL: y_6, TIME_SLEEP: SLEEP_TIME},
    {Y_PIXEL: y_6, TIME_SLEEP: SLEEP_TIME},
    {Y_PIXEL: y_6, TIME_SLEEP: SLEEP_TIME},
    {Y_PIXEL: y_6, TIME_SLEEP: SLEEP_TIME},
]
