Y_PIXEL = "Y_PIXEL"
TIME_SLEEP = "TIME_SLEEP"
SCAR_SLEEP_TIME = 0.08  # 射速
scar_data1 = [
    {Y_PIXEL: 20, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 20, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 20, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 20, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 20, TIME_SLEEP: SCAR_SLEEP_TIME},

]
scar_data2 = [
    {Y_PIXEL: 25, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 25, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 25, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 26, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 26, TIME_SLEEP: SCAR_SLEEP_TIME},
]
y_3=33
scar_data3 = [
    {Y_PIXEL: y_3, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: y_3, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: y_3, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: y_3, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: y_3, TIME_SLEEP: SCAR_SLEEP_TIME},
]
y_4=37
scar_data4 = [
    {Y_PIXEL: y_4, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: y_4, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: y_4, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: y_4, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: y_4, TIME_SLEEP: SCAR_SLEEP_TIME},
]
y_5=40
scar_data5 = [
    {Y_PIXEL: y_5, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: y_5, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: y_5, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: y_5, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: y_5, TIME_SLEEP: SCAR_SLEEP_TIME},
]
y_6=44
scar_data6 = [
    {Y_PIXEL: y_6, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: y_6, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: y_6, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: y_6, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: y_6, TIME_SLEEP: SCAR_SLEEP_TIME},
]
