Y_PIXEL = "Y_PIXEL"
TIME_SLEEP = "TIME_SLEEP"
SCAR_SLEEP_TIME = 0.08  # 射速
scar_data1 = [
    {Y_PIXEL: 20, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 20, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 20, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 20, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 20, TIME_SLEEP: SCAR_SLEEP_TIME},

]
scar_data2 = [
    {Y_PIXEL: 25, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 25, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 25, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 26, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 26, TIME_SLEEP: SCAR_SLEEP_TIME},
]
scar_data3 = [
    {Y_PIXEL: 26, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 26, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 26, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 27, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 27, TIME_SLEEP: SCAR_SLEEP_TIME},
]
scar_data4 = [
    {Y_PIXEL: 22, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 22, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 22, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 22, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 22, TIME_SLEEP: SCAR_SLEEP_TIME},
]
scar_data5 = [
    {Y_PIXEL: 22, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 22, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 22, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 22, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 22, TIME_SLEEP: SCAR_SLEEP_TIME},
]
scar_data6 = [
    {Y_PIXEL: 22, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 22, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 22, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 22, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 22, TIME_SLEEP: SCAR_SLEEP_TIME},
]
