Y_PIXEL = "Y_PIXEL"
TIME_SLEEP = "TIME_SLEEP"
SCAR_SLEEP_TIME = 0.08  # 射速
scar_data1 = [
    {Y_PIXEL: 11, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 11, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 10, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 10, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 10, TIME_SLEEP: SCAR_SLEEP_TIME},

]
scar_data2 = [
    {Y_PIXEL: 10, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 11, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 11, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 11, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 11, TIME_SLEEP: SCAR_SLEEP_TIME},
]
scar_data3 = [
    {Y_PIXEL: 13, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 13, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 14, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 14, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 14, TIME_SLEEP: SCAR_SLEEP_TIME},
]
scar_data4 = [
    {Y_PIXEL: 15, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 16, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 17, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 17, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 16, TIME_SLEEP: SCAR_SLEEP_TIME},
]
scar_data5 = [
    {Y_PIXEL: 16, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 16, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 16, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 16, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 16, TIME_SLEEP: SCAR_SLEEP_TIME},
]
scar_data6 = [
    {Y_PIXEL: 16, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 16, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 16, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 16, TIME_SLEEP: SCAR_SLEEP_TIME},
    {Y_PIXEL: 16, TIME_SLEEP: SCAR_SLEEP_TIME},
]
